# make sure contaienr port to be used with 80, thus we can check whether the GET request returns desired results
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-liveness
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    ports:
    - containerPort: 80
      protocol: TCP
    livenessProbe:
      httpGet:
        path: /
        port: 80
      
      #successThreshold: 1  
      #timeoutSeconds: 1
      #periodSeconds: 15  
      #failureThreshold: 3
