{
 "title": "GWM",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "zone", "label": "zone", "query": "dev35,stg35,qa35,prod" },
   { "name": "Prometheus", "label": "Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Wibapp Service Restarting",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_systemd_unit_state{ instance=~\"gwm.*\", name=\"wibapp.service\", state=\"activating\", zone=~\"$zone\"}",
     "legendFormat": "Active {{ instance}} : Restarting"
    }
   ]
  },
  {
   "title": "Wibapp Service Running",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_systemd_unit_state{ instance=~\"gwm.*\", name=\"wibapp.service\", state=\"active\", zone=~\"$zone\"}",
     "legendFormat": "Active {{ instance}} : Running"
    }
   ]
  },
  {
   "title": "Basic Clock Metrics ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Clock Sync Drift ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "node_timex_estimated_error_seconds{instance=~\"gwm.*\", zone=~\"$zone\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Clock Offset",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "node_timex_offset_seconds{instance=~\"gwm.*\", zone=~\"$zone\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Clock Max Error",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "node_timex_maxerror_seconds{instance=~\"gwm.*\", zone=~\"$zone\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Clock Sync Status",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "targets": [
      {
       "expr": "node_timex_sync_status{instance=~\"gwm.*\", zone=~\"$zone\"}",
       "legendFormat": "{{ instance }} "
      }
     ]
    }
   ]
  },
  {
   "title": "System Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Utilization (%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 -(avg by(instance) (rate(node_cpu_seconds_total{instance=~\"gwm.*\",job=\"node exporter\",zone=~\"$zone\",mode=\"idle\"}[2m]))* 100)",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "CPU Usage - User(%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(avg by(instance) (irate(node_cpu_seconds_total{instance=~\"gwm.*\",job=\"node exporter\",zone=~\"$zone\",mode=\"user\"}[2m])))",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "CPU Usage - System (%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(avg by(instance) (irate(node_cpu_seconds_total{instance=~\"gwm.*\",job=\"node exporter\",zone=~\"$zone\",mode=\"system\"}[2m])))",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "CPU Usage iowait",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg by(instance) (rate(node_cpu_seconds_total{instance=~\"gwm.*\", zone=~\"$zone\",mode=\"iowait\"}[2m]))",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "Memory Usage (%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100- (node_memory_MemAvailable_bytes{ instance=~\"gwm.*\", zone=~\"$zone\"} * 100) / node_memory_MemTotal_bytes{ instance=~\"gwm.*\", zone=~\"$zone\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Disk Space Usage % ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 - (node_filesystem_avail_bytes * 100) / node_filesystem_size_bytes { instance=~\"gwm.*\", zone=~\"$zone\", mountpoint=\"/\"}",
       "legendFormat": "{{ instance }} : {{device}}"
      }
     ]
    },
    {
     "title": "Disk Write",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "targets": [
      {
       "expr": "sum by (instance) (rate(node_disk_written_bytes_total{instance=~\"gwm.*\", zone=~\"$zone\"}[2m])) / 1024 ",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Disk Read",
     "type": "timeseries",
     "description": "Disk Read",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "targets": [
      {
       "expr": "sum by (instance) (rate(node_disk_read_bytes_total{instance=~\"gwm.*\", zone=~\"$zone\"}[2m])) / 1024",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Basic Load 1",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_load1 {instance=~\"gwm.*\", zone=~\"$zone\"}",
       "legendFormat": "{{ instance }} : Load1 "
      }
     ]
    },
    {
     "title": "Basic Load 5",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_load5 {instance=~\"gwm.*\", zone=~\"$zone\"}",
       "legendFormat": "{{ instance }} : Load 5"
      }
     ]
    },
    {
     "title": "Basic Load 15",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_load15 {instance=~\"gwm.*\", zone=~\"$zone\"}",
       "legendFormat": "{{ instance }} : Load 15"
      }
     ]
    }
   ]
  },
  {
   "title": "Application Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Java Memory Used",
     "type": "timeseries",
     "description": "Sum of the below elements:\n \"Code Cache\", \"Compressed Class Space\", \"Meta space\", \"PS Eden Space\", \"PS Old Gen\", and \"PS Survivor Space\" ",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "(sum by(instance) ((java_lang_MemoryPool_Usage_used{ instance=~\"gwm.*\",job=\"JMX exporter\", zone=~\"$zone.*\"})))",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Java  Heap Memory",
     "type": "timeseries",
     "description": "Sum of the below elements:\n \"Code Cache\", \"Compressed Class Space\", \"Meta space\", \"PS Eden Space\", \"PS Old Gen\", and \"PS Survivor Space\" ",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "(sum by(instance) ((java_lang_Memory_HeapMemoryUsage_committed{ instance=~\"gwm.*\",job=\"JMX exporter\", zone=~\"$zone.*\"})))",
       "legendFormat": "{{ instance }} comitted"
      },
      {
       "expr": "(sum by(instance) ((java_lang_Memory_HeapMemoryUsage_used{ instance=~\"gwm.*\",job=\"JMX exporter\",zone=~\"$zone.*\"})))",
       "legendFormat": "{{instance}} used"
      }
     ]
    },
    {
     "title": " Active Threads",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
     "targets": [
      {
       "expr": "com_good_gws_dcs_service_server_DCSClusterDataCounters_ActiveThreads{instance=~\"gwm.*\",zone=~\"$zone\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Java Memory Detailed Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_bytes_used{instance=~\"gwm.*\",zone=~\"$zone\"}",
       "legendFormat": " {{  instance }} : {{ area }}"
      }
     ]
    },
    {
     "title": "Average Bytes Queried ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "increase(com_good_gws_dcs_service_server_DCSClusterDataCounters_AverageBytesQueried{instance=~\"gwm.*\", zone=~\"$zone\"}[5m])",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": " Total Bytes Updated",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "increase(com_good_gws_dcs_service_server_DCSClusterDataCounters_TotalBytesUpdated{instance=~\"gwm.*\", zone=~\"$zone\"}[5m])",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": " Total Bytes Queried",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 99 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "increase(com_good_gws_dcs_service_server_DCSClusterDataCounters_TotalBytesQueried{instance=~\"gwm.*\", zone=~\"$zone\"}[5m])",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": " Average Bytes Updated",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 99 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "increase(com_good_gws_dcs_service_server_DCSClusterDataCounters_AverageBytesUpdated{instance=~\"gwm.*\", zone=~\"$zone\"}[5m])",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": " Successful Get Requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 107 },
     "targets": [
      {
       "expr": "increase(com_good_gws_dcs_service_server_DCSClusterDataCounters_SuccessfulGetRequests {instance=~\"gwm.*\", zone=~\"$zone\"}[2m])",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "Successful Update Requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 107 },
     "targets": [
      {
       "expr": "increase(com_good_gws_dcs_service_server_DCSClusterDataCounters_SuccessfulUpdateRequests {instance=~\"gwm.*\", zone=~\"$zone\"}[2m])",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Total Authentication Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 115 },
     "targets": [
      {
       "expr": "increase(com_good_gws_dcs_service_server_DCSClusterDataCounters_TotalAuthenticationCount{instance=~\"gwm.*\",zone=~\"$zone\"}[2m])",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": " Active Update Requests ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 115 },
     "targets": [
      {
       "expr": "increase(com_good_gws_dcs_service_server_DCSClusterDataCounters_ActiveUpdateRequests{instance=~\"gwm.*\", zone=~\"$zone\"}[2m])",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Active Get Requests ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 123 },
     "targets": [
      {
       "expr": "increase(com_good_gws_dcs_service_server_DCSClusterDataCounters_ActiveGetRequests{ instance=~\"gwm.*\", job=\"JMX exporter\", zone=~\"$zone\"}[2m])",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "Total DB Query Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 123 },
     "targets": [
      {
       "expr": "increase(com_good_gws_dcs_service_server_DCSClusterDataCounters_TotalDBQueryCount{instance=~\"gwm.*\", zone=~\"$zone\"}[2m])",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": " Total Get Requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 131 },
     "targets": [
      {
       "expr": "increase(com_good_gws_dcs_service_server_DCSClusterDataCounters_TotalGetRequests{instance=~\"gwm.*\", zone=~\"$zone\"}[2m])",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Total DB Update Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 131 },
     "targets": [
      {
       "expr": "increase(com_good_gws_dcs_service_server_DCSClusterDataCounters_TotalDBUpdateCount{instance=~\"gwm.*\", zone=~\"$zone\" }[5m])",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Total Update Requests ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 139 },
     "targets": [
      {
       "expr": "increase(com_good_gws_dcs_service_server_DCSClusterDataCounters_TotalUpdateRequests{instance=~\"gwm.*\", zone=~\"$zone\"}[2m])",
       "legendFormat": "{{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Net_Interface_eth0",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Traffic In (MB)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 148 },
     "targets": [
      {
       "expr": "sum by (instance)(rate(node_network_receive_bytes_total{instance=~\"gwm.*\", zone=~\"$zone\" ,device=\"eth0\"}[2m])) / 1024 / 1024",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Traffic Out (MB)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 148 },
     "targets": [
      {
       "expr": "sum by (instance)(rate(node_network_transmit_bytes_total{instance=~\"gwm.*\", zone=~\"$zone\" ,device=\"eth0\"}[2m])) / 1024 / 1024",
       "legendFormat": "{{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "IPV4 TCP Network Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Traffic",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 157 },
     "repeat": "node",
     "yaxes": [
      {
       "format": "bytes",
       "label": "bits/second in (-) / bits out (+)"
      }
     ],
     "targets": [
      {
       "expr": "irate(node_network_receive_bytes_total{instance=~'gwm.*', zone=~\"$zone\", device=\"eth0\"}[5m])*8 or irate(node_network_receive_bytes{instance=~'$gwm.*', zone=\"$zone\", device=\"eth0\"}[5m])*8",
       "legendFormat": "{{instance }}_in"
      },
      {
       "expr": "irate(node_network_transmit_bytes_total{instance=~\"gwm.*\",zone=~\"$zone\", device=\"eth0\"}[5m])*8 or irate(node_network_transmit_bytes{instance=~\"gwm.*\", zone=\"$zone\", device=\"eth0\"}[5m])*8",
       "legendFormat": "{{instance}} _out"
      }
     ]
    },
    {
     "title": "TCP Current Established ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 157 },
     "targets": [
      {
       "expr": "node_netstat_Tcp_CurrEstab{instance=~\"gwm.*\", zone=~\"$zone\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "TCP Active Opens",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 165 },
     "targets": [
      {
       "expr": "rate(node_netstat_Tcp_ActiveOpens {instance=~\"gwm.*\", zone=~\"$zone\"}[2m])",
       "legendFormat": "{{ instance}}"
      }
     ]
    },
    {
     "title": "TCP Passive Opens",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 165 },
     "targets": [
      {
       "expr": "rate(node_netstat_Tcp_PassiveOpens {instance=~\"gwm.*\", zone=~\"$zone\"}[2m])",
       "legendFormat": "{{ instance}}"
      }
     ]
    },
    {
     "title": "TCP InSegs",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 173 },
     "targets": [
      {
       "expr": "rate(node_netstat_Tcp_InSegs {instance=~\"gwm.*\", zone=~\"$zone\"}[2m])",
       "legendFormat": "{{ instance}}"
      }
     ]
    },
    {
     "title": "TCP OutSegs",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 173 },
     "targets": [
      {
       "expr": "rate(node_netstat_Tcp_OutSegs {instance=~\"gwm.*\", zone=~\"$zone\"}[2m])",
       "legendFormat": "{{ instance}}"
      }
     ]
    },
    {
     "title": "TCP Retran Segs",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 181 },
     "targets": [
      {
       "expr": "rate(node_netstat_Tcp_RetransSegs{instance=~\"gwm.*\", zone=~\"$zone\"}[2m])",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "TCP OutRsts",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 181 },
     "targets": [
      {
       "expr": "rate(node_netstat_Tcp_OutRsts{instance=~\"gwm.*\", zone=~\"$zone\"}[2m])",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "TCP InErrs",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 189 },
     "targets": [
      {
       "expr": "rate(node_netstat_Tcp_InErrs{instance=~\"gwm.*\", zone=~\"$zone\"}[2m])",
       "legendFormat": "{{ instance }} "
      }
     ]
    }
   ]
  },
  {
   "title": "IPV4 UDP Network Metrics ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "UDP  InDatagrams",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 198 },
     "targets": [
      {
       "expr": "rate(node_netstat_Udp_InDatagrams{ instance=~\"gwm.*\", zone=~\"$zone\"}[2m])",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "UDP  OutDatagrams",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 198 },
     "targets": [
      {
       "expr": "rate(node_netstat_Udp_OutDatagrams{ instance=~\"gwm.*\", zone=~\"$zone\"}[2m])",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "UDP NoPorts ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 206 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_netstat_Udp_NoPorts{instance=~\"gwm.*\", zone=~\"$zone\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "UDP InErrors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 206 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_netstat_Udp_InErrors{instance=~\"gwm.*\", zone=~\"$zone\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    }
   ]
  }
 ]
}