# Create 3 apache:2.2 pods using K8S ReplicaSet
--- 
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-mainui
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mainui
    matchExpressions:
    - {key: ver, operator: In, values: ["2.2"]}
  template:
    metadata:
      name: apache-pod
      labels:
        app: mainui
        ver: "2.2"
    spec:
      containers:
      - name: httpd
        image: httpd:2.2
        ports:
        - containerPort: 80
