# It's important you create the yaml file in the manifest directory. 
# Please reference a lecture note. 

apiVersion: v1
kind: Pod
metadata:
  name: mydb-node1
spec:
  containers:
  - name: mydb
    image: redis
    ports:
    - containerPort: 80
      protocol: TCP
